import DemoApp from './DemoApp';
import {canUseLocalDemo} from './demo-access';
import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,NavLink,Navigate,Route,Routes,useNavigate}from'react-router-dom';import{LayoutDashboard,Users,KanbanSquare,MessageCircle,CalendarClock,LogOut,Shield,Upload,Plus}from'lucide-react';import{api,supabase}from'./lib/api';import * as XLSX from 'xlsx';import './style.css';
type Lead={id:string;name:string;kind:string;city:string|null;interest:string|null;stage:string;lead_phones:{phone:string}[]};const stageNames:Record<string,string>={new:'Novo',contacted:'Contatado',interested:'Interessado',negotiation:'Negociação',won:'Ganho',lost:'Perdido'};
function Login({onLogin,onDemo}:{onLogin:()=>void;onDemo?:()=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);return <div className="login"><form className="login-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setError(error.message);else onLogin()}}><div className="logo">◆ TITAN <span>CRM 360</span></div><h1>Entrar no painel</h1><p>Acesso exclusivo da equipe comercial.</p><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?'Entrando...':'Entrar'}</button>{onDemo&&<button type="button" className="secondary" onClick={onDemo}>Entrar em modo demonstração (local)</button>}<small>Recebeu um convite? Use o link enviado ao seu e-mail para ativar seu acesso.</small></form></div>}
function Dashboard(){const[stats,setStats]=useState<{leads:number;open:number;tasksDue:number;wonAmount:number}|null>(null);const[error,setError]=useState('');useEffect(()=>{api<typeof stats>('/dashboard').then(setStats).catch(e=>setError(e.message))},[]);return <><div className="page-head"><h1>Visão geral</h1><p>Seu trabalho comercial, em um só lugar.</p></div>{error&&<div className="error">{error}</div>}<div className="stat-grid">{[['Leads',stats?.leads],['Oportunidades abertas',stats?.open],['Follow-ups vencidos',stats?.tasksDue],['Vendas ganhas (R$)',stats?.wonAmount?.toLocaleString('pt-BR',{minimumFractionDigits:2})]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong>{value??'...'}</strong></div>)}</div><div className="panel"><h2>Próximas ações</h2><p>Importe seus leads, avance as oportunidades no funil e acompanhe os retornos.</p></div></>}
function Leads({board=false}:{board?:boolean}){const[items,setItems]=useState<Lead[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[report,setReport]=useState('');const[showNew,setShowNew]=useState(false);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[interest,setInterest]=useState('');const[search,setSearch]=useState('');async function load(){setLoading(true);try{const r=await api<{items:Lead[]}>('/leads');setItems(r.items);setError('')}catch(e){setError(String(e))}finally{setLoading(false)}}useEffect(()=>{load()},[]);async function onFile(f:File){setReport('Lendo planilha...');try{const buf=await f.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:''});if(rows.length>5000)throw new Error('Limite de 5.000 linhas por arquivo');const r=await api<{created:number;rejected:number;errors:{line:number;reason:string}[]}>('/leads/import',{method:'POST',body:JSON.stringify({rows})});setReport(`Importados: ${r.created}. Rejeitados: ${r.rejected}. ${r.errors.slice(0,3).map(e=>e.reason).join('; ')}`);await load()}catch(e){setReport(String(e))}}
async function changeStage(l:Lead,stage:string){try{await api(`/leads/${l.id}/stage`,{method:'PATCH',body:JSON.stringify({stage})});setItems(v=>v.map(x=>x.id===l.id?{...x,stage}:x))}catch(e){setError(String(e))}}
const filtered=items.filter(x=>(x.name+' '+x.city+' '+x.interest+' '+x.lead_phones.map(p=>p.phone).join(' ')).toLowerCase().includes(search.toLowerCase()));return <><div className="page-head"><h1>{board?'Funil comercial':'Leads e clientes'}</h1><p>{board?'Acompanhe cada etapa da negociação.':'Cadastre, importe e trate seus contatos.'}</p></div><div className="toolbar"><input placeholder="Buscar cliente, telefone ou cidade" value={search} onChange={e=>setSearch(e.target.value)}/><label className="btn secondary"><Upload size={16}/> Importar CSV/XLSX<input type="file" accept=".csv,.xlsx,.xls" hidden onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/></label><button onClick={()=>setShowNew(v=>!v)}><Plus size={16}/> Novo lead</button></div>{showNew&&<form className="panel form-row" onSubmit={async e=>{e.preventDefault();try{await api('/leads',{method:'POST',body:JSON.stringify({nome:name,telefone:phone,interesse:interest})});setName('');setPhone('');setInterest('');setShowNew(false);await load()}catch(e){setError(String(e))}}}><input required placeholder="Nome" value={name} onChange={e=>setName(e.target.value)}/><input required placeholder="Telefone" value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="Interesse" value={interest} onChange={e=>setInterest(e.target.value)}/><button>Salvar</button></form>}{report&&<div className="notice">{report}</div>}{error&&<div className="error">{error}</div>}{loading?<p>Carregando...</p>:board?<div className="board">{Object.entries(stageNames).map(([stage,title])=><div className="board-col" key={stage}><h3>{title} <span>{filtered.filter(x=>x.stage===stage).length}</span></h3>{filtered.filter(x=>x.stage===stage).map(x=><div className="lead-card" key={x.id}><b>{x.name}</b><small>{x.interest||'Sem produto'}</small><select aria-label="Alterar etapa" value={x.stage} onChange={e=>changeStage(x,e.target.value)}>{Object.entries(stageNames).map(([key,n])=><option key={key} value={key}>{n}</option>)}</select></div>)}</div>)}</div>:<div className="panel table-wrap"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Interesse</th><th>Cidade</th><th>Etapa</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td><b>{l.name}</b><small>{l.kind}</small></td><td>{l.lead_phones?.map(p=>p.phone).join(', ')}</td><td>{l.interest||'—'}</td><td>{l.city||'—'}</td><td><select value={l.stage} onChange={e=>changeStage(l,e.target.value)}>{Object.entries(stageNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td></tr>)}</tbody></table>{!filtered.length&&<p>Nenhum lead encontrado.</p>}</div>}</>}
function WhatsApp(){
 const[status,setStatus]=useState('Consultando...');
 const[groups,setGroups]=useState<{id:string;name:string;pictureUrl?:string;archived?:boolean}[]>([]);
 const[filter,setFilter]=useState<'all'|'archived'|'active'>('all');
 const[selected,setSelected]=useState<string[]>([]);
 const[error,setError]=useState('');const[loading,setLoading]=useState(false);
 useEffect(()=>{api<{provider:string;status:string}>('/whatsapp/status').then(r=>setStatus(`${r.provider}: ${r.status}`)).catch(e=>setStatus(String(e)))},[]);
 const filtered=groups.filter(g=>filter==='all'||(filter==='archived'?g.archived:!g.archived));
 const archived=groups.filter(g=>g.archived).length;
 async function sync(){setError('');setLoading(true);try{const result=await api<typeof groups>('/whatsapp/groups');setGroups(result);setSelected(current=>current.filter(id=>result.some(g=>g.id===id)));}catch(e){setError(String(e))}finally{setLoading(false)}}
 return <><div className="page-head"><h1>WhatsApp e grupos</h1><p>Todos os grupos da conta conectada, arquivados e não arquivados. Contatos individuais não aparecem.</p></div>
 <div className="panel"><h2>Conexão</h2><p>{status}</p><button disabled={loading} onClick={sync}>{loading?'Sincronizando...':'Sincronizar todos os grupos'}</button>
 {error&&<div className="error" role="alert">{error}</div>}
 <p><strong>{groups.length}</strong> grupos encontrados: {archived} arquivados e {groups.length-archived} não arquivados. {selected.length} selecionados.</p>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}>
 <button onClick={()=>setFilter('all')}>Todos ({groups.length})</button><button onClick={()=>setFilter('active')}>Não arquivados ({groups.length-archived})</button><button onClick={()=>setFilter('archived')}>Arquivados ({archived})</button>
 <button onClick={()=>setSelected(current=>[...new Set([...current,...filtered.map(g=>g.id)])])}>Selecionar exibidos</button><button onClick={()=>setSelected([])}>Limpar seleção</button>
 </div>
 {filtered.map(g=><label className="lead-card" key={g.id} style={{display:'flex',alignItems:'center',gap:12,cursor:'pointer'}}>
 <input type="checkbox" checked={selected.includes(g.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,g.id]:current.filter(id=>id!==g.id))}/>
 {g.pictureUrl?<img src={g.pictureUrl} alt="" style={{height:36,width:36,borderRadius:'50%',objectFit:'cover'}}/>:null}
 <span><strong>{g.name}</strong> <small>{g.archived?'Arquivado':'Não arquivado'}</small></span></label>)}
 <p className="muted">A seleção é local nesta versão. Nenhum envio automático é feito. A lista requer o WPPConnect Server conectado.</p>
 </div></>
}

type TeamUser={id:string;full_name:string;role:'leader'|'seller';email:string;confirmed:boolean};
function TeamUsers(){const[items,setItems]=useState<TeamUser[]>([]);const[name,setName]=useState('');const[email,setEmail]=useState('');const[role,setRole]=useState<'leader'|'seller'>('seller');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');async function load(){try{const r=await api<{items:TeamUser[]}>('/users');setItems(r.items)}catch(e){setError(String(e))}}useEffect(()=>{load()},[]);async function invite(e:React.FormEvent){e.preventDefault();setError('');setMessage('');setBusy(true);try{const r=await api<{message:string}>('/users/invite',{method:'POST',body:JSON.stringify({full_name:name,email,role})});setMessage(r.message);setName('');setEmail('');setRole('seller');await load()}catch(e){setError(String(e))}finally{setBusy(false)}}async function changeRole(user:TeamUser,newRole:'leader'|'seller'){if(!window.confirm(`Alterar o perfil de ${user.full_name||user.email} para ${newRole==='leader'?'Líder':'Vendedor'}?`))return;try{await api(`/users/${user.id}/role`,{method:'PATCH',body:JSON.stringify({role:newRole})});await load()}catch(e){setError(String(e))}}return <><div className="page-head"><h1>Gestão de usuários</h1><p>Convide vendedores sem abrir o painel do Supabase.</p></div><form className="panel team-form" onSubmit={invite}><h2>Convidar usuário</h2><label>Nome completo<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do vendedor"/></label><label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="vendedor@exemplo.com"/></label><label>Perfil<select value={role} onChange={e=>setRole(e.target.value as 'leader'|'seller')}><option value="seller">Vendedor</option><option value="leader">Líder</option></select></label><button disabled={busy}>{busy?'Enviando...':'Enviar convite por e-mail'}</button><small>O usuário receberá um convite para configurar o acesso. Somente líderes podem convidar e alterar perfis.</small></form>{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}<div className="panel table-wrap"><h2>Equipe</h2><table><thead><tr><th>Nome</th><th>E-mail</th><th>Acesso</th><th>Perfil</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td>{u.full_name||'Sem nome'}</td><td>{u.email}</td><td>{u.confirmed?'Confirmado':'Pendente'}</td><td><select value={u.role} onChange={e=>changeRole(u,e.target.value as 'leader'|'seller')}><option value="seller">Vendedor</option><option value="leader">Líder</option></select></td></tr>)}</tbody></table>{!items.length&&<p>Nenhum usuário encontrado.</p>}</div></>}
function Roadmap(){return <><div className="page-head"><h1>Campanhas</h1><p>Agendamento e envio ainda em desenvolvimento.</p></div><div className="panel"><h2>Próxima fase</h2><p>Aqui serão criadas e revisadas campanhas. Nenhum disparo automático está ativado nesta versão.</p></div></>}
function SetPassword(){const[password,setPassword]=useState('');const[repeat,setRepeat]=useState('');const[error,setError]=useState('');const[done,setDone]=useState(false);const[ready,setReady]=useState(false);useEffect(()=>{supabase.auth.getSession().then(({data})=>setReady(!!data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(session)setReady(true)});return()=>subscription.unsubscribe()},[]);return <div className="login"><form className="login-card" onSubmit={async e=>{e.preventDefault();setError('');if(password.length<8||password!==repeat){setError('Use no mínimo 8 caracteres e confirme a mesma senha');return}const {error}=await supabase.auth.updateUser({password});if(error)setError(error.message);else setDone(true)}}><div className="logo">◆ TITAN <span>CRM 360</span></div><h1>Definir senha</h1>{done?<><p>Senha definida. Você já pode acessar o TITAN.</p><a href="/">Ir para o painel</a></>:<>{!ready&&<p>Confirmando seu convite... Se não aparecer a sessão, abra novamente o link do e-mail.</p>}<label>Nova senha<input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirme a senha<input required type="password" minLength={8} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button disabled={!ready}>Salvar minha senha</button></>}</form></div>}
function App(){const[demo,setDemo]=useState(false);const demoAllowed=canUseLocalDemo(import.meta.env.DEV,window.location.hostname);const[session,setSession]=useState<boolean|null>(null);const[profile,setProfile]=useState<{full_name:string;role:string}|null>(null);const navigate=useNavigate();useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(!!data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setSession(!!s));return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(session)api<{full_name:string;role:string}>('/me').then(setProfile).catch(()=>setProfile(null));else setProfile(null)},[session]);if(demo && demoAllowed)return <DemoApp onExit={()=>setDemo(false)}/>;if(window.location.pathname==='/set-password')return <SetPassword/>;if(session===null)return <div className="loading">Carregando TITAN...</div>;if(!session)return <Login onLogin={()=>setSession(true)} onDemo={demoAllowed?()=>setDemo(true):undefined}/>;const nav=[{to:'/',icon:LayoutDashboard,label:'Visão geral'},{to:'/leads',icon:Users,label:'Leads'},{to:'/funil',icon:KanbanSquare,label:'Funil'},{to:'/whatsapp',icon:MessageCircle,label:'WhatsApp / Grupos'},{to:'/campanhas',icon:CalendarClock,label:'Campanhas'},...(profile?.role==='leader'?[{to:'/usuarios',icon:Shield,label:'Gestão de usuários'}]:[])];return <div className="app"><aside><div className="logo">◆ TITAN <span>CRM 360</span></div><nav>{nav.map(n=><NavLink key={n.to} to={n.to} end={n.to==='/'}><n.icon size={18}/>{n.label}</NavLink>)}</nav><div className="sidebar-bottom"><div><Shield size={16}/> {profile?.full_name||'Usuário'} <small>{profile?.role==='leader'?'Líder':'Vendedor'}</small></div><button className="logout" onClick={async()=>{await supabase.auth.signOut();navigate('/')}}><LogOut size={16}/> Sair</button></div></aside><main><Routes><Route path="/" element={<Dashboard/>}/><Route path="/leads" element={<Leads/>}/><Route path="/funil" element={<Leads board/>}/><Route path="/whatsapp" element={<WhatsApp/>}/><Route path="/campanhas" element={<Roadmap/>}/><Route path="/usuarios" element={profile?.role==='leader'?<TeamUsers/>:<Navigate to="/"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
