import 'dotenv/config';import express from 'express';import cors from 'cors';import helmet from 'helmet';import {z} from 'zod';import {authenticate,leaderOnly,type AuthRequest} from './lib/auth.js';import {adminDb} from './lib/supabase.js';import {prepareLeads,leadSchema} from './services/import.js';import {getProvider} from './providers/index.js';
const app=express();app.use(helmet());app.use(cors({origin:process.env.FRONTEND_ORIGIN||'http://localhost:5173'}));app.use(express.json({limit:'2mb'}));app.get('/health',(_req,res)=>res.json({status:'ok',service:'titan-api'}));app.use('/api',authenticate);
app.get('/api/me',async(req:AuthRequest,res)=>{const {data,error}=await adminDb().from('profiles').select('id,full_name,role').eq('id',req.userId!).single();if(error)return res.status(500).json({error:error.message});res.json(data)});
app.get('/api/dashboard',async(req:AuthRequest,res)=>{const db=adminDb();const [leads,open,tasks,won]=await Promise.all([db.from('leads').select('id',{count:'exact',head:true}),db.from('opportunities').select('id',{count:'exact',head:true}).neq('stage','won').neq('stage','lost'),db.from('tasks').select('id',{count:'exact',head:true}).eq('done',false).lte('due_at',new Date().toISOString()),db.from('opportunities').select('amount').eq('stage','won')]);const errors=[leads.error,open.error,tasks.error,won.error].filter(Boolean);if(errors.length)return res.status(500).json({error:'Falha ao consultar indicadores'});res.json({leads:leads.count??0,open:open.count??0,tasksDue:tasks.count??0,wonAmount:(won.data||[]).reduce((a,r)=>a+Number(r.amount||0),0)})});
app.get('/api/leads',async(req:AuthRequest,res)=>{const db=adminDb();let q=db.from('leads').select('id,name,kind,email,cpf_cnpj,city,address,interest,source,stage,created_at,lead_phones(phone)',{count:'exact'}).order('created_at',{ascending:false}).limit(200);if(req.role!=='leader')q=q.eq('owner_id',req.userId!);const {data,error,count}=await q;if(error)return res.status(500).json({error:error.message});res.json({items:data,count})});
app.post('/api/leads',async(req:AuthRequest,res)=>{const parsed=leadSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.flatten()});const l=parsed.data;const db=adminDb();const {data,error}=await db.from('leads').insert({name:l.nome,kind:l.tipo,email:l.email||null,cpf_cnpj:l.cpf_cnpj||null,city:l.cidade||null,address:l.endereco||null,interest:l.interesse||null,source:l.origem||'manual',owner_id:req.userId}).select('id').single();if(error)return res.status(400).json({error:error.message});const {error:phoneError}=await db.from('lead_phones').insert({lead_id:data.id,phone:l.telefone});if(phoneError){await db.from('leads').delete().eq('id',data.id);return res.status(409).json({error:phoneError.message})}res.status(201).json(data)});
app.post('/api/leads/import',async(req:AuthRequest,res)=>{const check=z.object({rows:z.array(z.record(z.unknown())).max(5000)}).safeParse(req.body);if(!check.success)return res.status(400).json({error:'Envie rows com até 5.000 registros'});const {valid,errors}=prepareLeads(check.data.rows);const db=adminDb();let created=0;for(const l of valid){const {data:exists}=await db.from('lead_phones').select('lead_id').eq('phone',l.telefone).maybeSingle();if(exists){errors.push({line:0,reason:`Telefone já cadastrado: ${l.telefone}`});continue}const {data,error}=await db.from('leads').insert({name:l.nome,kind:l.tipo,email:l.email||null,cpf_cnpj:l.cpf_cnpj||null,city:l.cidade||null,address:l.endereco||null,interest:l.interesse||null,source:l.origem||'planilha',owner_id:req.userId}).select('id').single();if(error){errors.push({line:0,reason:error.message});continue}const {error:pErr}=await db.from('lead_phones').insert({lead_id:data.id,phone:l.telefone});if(pErr){await db.from('leads').delete().eq('id',data.id);errors.push({line:0,reason:pErr.message})}else created++}res.json({created,rejected:errors.length,errors:errors.slice(0,100)})});
app.patch('/api/leads/:id/stage',async(req:AuthRequest,res)=>{const stage=z.enum(['new','contacted','interested','negotiation','won','lost']).safeParse(req.body.stage);if(!stage.success)return res.status(400).json({error:'Etapa inválida'});let q=adminDb().from('leads').update({stage:stage.data}).eq('id',req.params.id);if(req.role!=='leader')q=q.eq('owner_id',req.userId!);const {data,error}=await q.select('id,stage').maybeSingle();if(error)return res.status(500).json({error:error.message});if(!data)return res.status(404).json({error:'Lead não encontrado'});res.json(data)});

const inviteSchema=z.object({email:z.string().trim().email().max(254),full_name:z.string().trim().min(2).max(120),role:z.enum(['seller','leader']).default('seller')});
app.get('/api/users',leaderOnly,async(_req,res)=>{try{const {data,error}=await adminDb().from('profiles').select('id,full_name,role,created_at').order('created_at',{ascending:false});if(error)return res.status(500).json({error:'Não foi possível listar usuários'});const auth=await adminDb().auth.admin.listUsers({page:1,perPage:1000});if(auth.error)return res.status(500).json({error:'Não foi possível obter usuários autenticados'});res.json({items:(data||[]).map(row=>({...row,email:auth.data.users.find(u=>u.id===row.id)?.email||'',confirmed:!!auth.data.users.find(u=>u.id===row.id)?.email_confirmed_at}))})}catch{return res.status(500).json({error:'Falha ao consultar usuários'})}});
app.post('/api/users/invite',leaderOnly,async(req:AuthRequest,res)=>{const parsed=inviteSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Informe nome, e-mail válido e perfil'});try{const db=adminDb();const {email,full_name,role}=parsed.data;const redirect=process.env.INVITE_REDIRECT_URL||'http://localhost:5173/set-password';const {data,error}=await db.auth.admin.inviteUserByEmail(email,{redirectTo:redirect,data:{full_name}});if(error)return res.status(400).json({error:error.message});if(!data.user)return res.status(500).json({error:'Convite não retornou usuário'});
const {error:profileError}=await db.from('profiles').upsert({id:data.user.id,full_name,role},{onConflict:'id'});if(profileError)return res.status(500).json({error:'Convite criado, mas não foi possível atribuir o perfil. Confira no Supabase antes de reenviar.'});res.status(201).json({id:data.user.id,email:data.user.email,full_name,role,message:'Convite enviado. O usuário deverá definir a senha por e-mail.'})}catch{return res.status(500).json({error:'Não foi possível enviar convite'})}});
app.patch('/api/users/:id/role',leaderOnly,async(req:AuthRequest,res)=>{const role=z.enum(['seller','leader']).safeParse(req.body?.role);const id=z.string().uuid().safeParse(req.params.id);if(!role.success||!id.success)return res.status(400).json({error:'Dados inválidos'});if(id.data===req.userId && role.data!=='leader')return res.status(400).json({error:'Você não pode retirar seu próprio acesso de líder'});const {data,error}=await adminDb().from('profiles').update({role:role.data}).eq('id',id.data).select('id,role').maybeSingle();if(error)return res.status(500).json({error:'Falha ao alterar perfil'});if(!data)return res.status(404).json({error:'Usuário não encontrado'});res.json(data)});
app.get('/api/whatsapp/status',async(_req,res)=>{try{const p=getProvider();res.json({provider:p.id,status:await p.getStatus('titan')})}catch(e){res.status(503).json({error:String(e)})}});
app.get('/api/whatsapp/groups',leaderOnly,async(_req,res)=>{try{res.json(await getProvider().listGroups('titan'))}catch(e){res.status(503).json({error:e instanceof Error?e.message:'Falha de conexão'})}});
app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error(err);res.status(500).json({error:'Erro interno'})});
const port=Number(process.env.PORT||3001);if(process.env.NODE_ENV!=='test')app.listen(port,()=>console.log(`TITAN API: http://localhost:${port}`));export {app};
